version: '3'

services:
  # rebirth 서비스 (Spring Boot 애플리케이션)
  rebirth:
    image: rebirth-image
    container_name: rebirth_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"   # 호스트 포트 8081 → 컨테이너 포트 8080
    networks:
      - app-network

  # cardissuer 서비스
  cardissuer:
    image: cardissuer-image
    container_name: cardissuer_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8082:8080"   # 호스트 포트 8082 → 컨테이너 포트 8080
    networks:
      - app-network
  # bank 서비스
  bank:
    image: bank-image
    container_name: bank_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8083:8080"   # 호스트 포트 8083 → 컨테이너 포트 8080
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
  pgdata: