version: '3'

services:
  # nginx 리버스 프록시
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    # EC2 내부 디렉토리 -> 컨테이너로 마운트
    volumes:
      - /home/ubuntu/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - rebirth
    networks:
      - app-network


  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Spring Boot 앱 컨테이너
  rebirth:
    image: rebirth-image
    container_name: rebirth_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"   # 호스트 8081 → 컨테이너 8080
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
  pgdata: